version: v1.0
name: Pipeline 2
blocks:
  - name: Deploy
    task:
      jobs:
        - name: Deploy to prod
          commands:
            - echo "deploying to prod"
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
